// Generated by CoffeeScript 2.4.1
(function() {
  // Hello World in Many Programming Languages!!!
  // Authors:
  // @author Ruben Andre Barreiro

  // Prints "Hello World!!!" to the terminal window
  console.log("Hello World!!!");

}).call(this);
