include $(GNUSTEP_MAKEFILES)/common.make
# make a simple program in Objective-C, call it HelloWorld
TOOL_NAME = HelloWorld
# The implementation Objective-C file which is going to be compiled
HelloWorld_OBJC_FILES = HelloWorld.m
# Header files of your project
# Define compilation flags
ADDITIONAL_CPPFLAGS = -Wall -Wno-import
# Include rules for creating a command line tool for Objective-C
include $(GNUSTEP_MAKEFILES)/tool.make